---

- name: 1. Aktualizace cache baliku
  become: true
  ansible.builtin.apt:
    update_cache: true
    force: true
  
- name: 2. Instalace mariadb
  become: true
  ansible.builtin.package:
    name: 
      - mariadb-server
      - mariadb-client
    state: present
    force: true

- name: 3. Povoleni sluzby mariadb
  ansible.builtin.service:
    name: mariadb
    enabled: yes
  become: true

- name: 4. Zalozeni databaze
  become: true
  ansible.builtin.shell: mysql -uroot -e "CREATE DATABASE wordpress_db;"
  args:
    executable: /bin/bash

- name: 5. Zalozeni uzivatele a nastaveni prav
  become: true
  ansible.builtin.shell: mysql -uroot -e "GRANT ALL ON wordpress_db.* TO 'wpuser'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  args:
    executable: /bin/bash

- name: 6. Aktualizace opravneni
  become: true
  ansible.builtin.shell: mysql -uroot -e "FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash

