#!/bin/bash

echo "Aktivuji UFW..."
ufw --force enable

ufw default reject incoming

echo "  povoluji SSH (port 22)"
ufw allow in ssh

echo "  povoluji HTTP (port 80)"
ufw allow in http

echo "  povoluji HTTPS (port 443)"
ufw allow in https


